package appmeta

// curatedLabels is the static package → display name map. Curated for
// max coverage of Chinese consumer apps (since HNC's primary audience
// is in Chinese-speaking regions) + global apps users commonly have +
// system apps on common ROMs (ColorOS, MIUI, OxygenOS, AOSP).
//
// Maintenance: add entries as you encounter apps users have. The user
// override file at /data/local/hnc/etc/app_labels.json takes precedence,
// so out-of-date entries here don't block users from fixing them.
//
// Ordering: by category (loosely), then alphabetic by package. Not
// performance-critical — Go map literals compile to a hash table.
var curatedLabels = map[string]string{
	// ─── Tencent ──────────────────────────────────────────────────
	"com.tencent.mm":                 "微信",
	"com.tencent.mobileqq":           "QQ",
	"com.tencent.qqlite":             "QQ 轻聊版",
	"com.tencent.wework":             "企业微信",
	"com.tencent.wetype":             "微信键盘",
	"com.tencent.qqmusic":            "QQ 音乐",
	"com.tencent.qqlive":             "腾讯视频",
	"com.tencent.qqsports":           "腾讯体育",
	"com.tencent.docs":               "腾讯文档",
	"com.tencent.weishi":             "微视",
	"com.tencent.news":               "腾讯新闻",
	"com.tencent.qqmail":             "QQ 邮箱",
	"com.tencent.karaoke":            "全民 K 歌",
	"com.tencent.reading":            "腾讯新闻",
	"com.tencent.weread":             "微信读书",
	"com.tencent.peng":               "腾讯视频",
	"com.tencent.tmgp.sgame":         "王者荣耀",
	"com.tencent.tmgp.pubgmhd":       "和平精英",
	"com.tencent.tmgp.cf":            "穿越火线",
	"com.tencent.lemon":              "腾讯文档",
	"com.tencent.lightapp":           "腾讯轻应用",

	// ─── ByteDance ────────────────────────────────────────────────
	"com.ss.android.ugc.aweme":          "抖音",
	"com.ss.android.ugc.aweme.lite":     "抖音极速版",
	"com.ss.android.article.news":       "今日头条",
	"com.ss.android.article.lite":       "今日头条极速版",
	"com.zhiliaoapp.musically":          "TikTok",
	"com.lemon.lv":                      "剪映",
	"com.bytedance.ee.bear":             "飞书",
	"com.larksuite.suite":               "Lark",

	// ─── Alibaba ──────────────────────────────────────────────────
	"com.taobao.taobao":                 "淘宝",
	"com.taobao.idlefish":               "闲鱼",
	"com.taobao.live":                   "淘宝直播",
	"com.tmall.wireless":                "天猫",
	"com.alibaba.android.rimet":         "钉钉",
	"com.alipay.android.app":            "支付宝",
	"com.eg.android.AlipayGphone":       "支付宝",
	"com.amap.android.taobaotraveler":   "高德地图",
	"com.autonavi.minimap":              "高德地图",
	"com.UCMobile":                      "UC 浏览器",
	"com.youku.phone":                   "优酷",

	// ─── 短视频 + 社交 ────────────────────────────────────────
	"com.smile.gifmaker":                "快手",
	"com.kuaishou.nebula":               "快手极速版",
	"com.xingin.xhs":                    "小红书",
	"com.sina.weibo":                    "微博",
	"com.zhihu.android":                 "知乎",
	"com.jingdong.app.mall":             "京东",
	"com.jingdong.lite":                 "京东极速版",
	"com.xunmeng.pinduoduo":             "拼多多",
	"com.sankuai.meituan":               "美团",
	"me.ele":                            "饿了么",
	"com.dianping.v1":                   "大众点评",
	"ctrip.android.view":                "携程",
	"com.douban.frodo":                  "豆瓣",
	"cn.soulapp.android":                "Soul",
	"com.immomo.momo":                   "陌陌",
	"com.tantanapp.android":             "探探",
	"com.duomai.shuanglu":               "双鹿",

	// ─── 网易 / 音乐 ──────────────────────────────────────────
	"com.netease.cloudmusic":            "网易云音乐",
	"com.netease.cloudmusic.lite":       "网易云音乐极速版",
	"com.netease.mail":                  "网易邮箱大师",
	"com.netease.newsreader.activity":   "网易新闻",
	"com.netease.onmyoji":               "阴阳师",
	"com.kugou.android":                 "酷狗音乐",
	"cn.kuwo.player":                    "酷我音乐",
	"com.kugou.android.lite":            "酷狗音乐极速版",

	// ─── 米哈游 / 二次元 / 游戏 ────────────────────────────────
	"com.miHoYo.GenshinImpact":          "原神",
	"com.miHoYo.GenshinImpact.bilibili": "原神 B 服",
	"com.miHoYo.bh3":                    "崩坏 3",
	"com.miHoYo.bh3.bilibili":           "崩坏 3 B 服",
	"com.miHoYo.hkrpg":                  "崩坏: 星穹铁道",
	"com.miHoYo.hkrpg.bilibili":         "崩坏: 星穹铁道 B 服",
	"com.miHoYo.cloudgames.genshin":     "云·原神",
	"com.miHoYo.cloudgames.hkrpg":       "云·星穹铁道",
	"tv.danmaku.bili":                   "哔哩哔哩",
	"tv.danmaku.bilibilihd":             "哔哩哔哩 HD",
	"com.bilibili.app.in":               "哔哩哔哩 (国际版)",
	"com.bilibili.app.blue":             "哔哩哔哩 (定制)",

	// ─── 银行 / 金融 ──────────────────────────────────────────
	"com.icbc":                          "工商银行",
	"com.chinamworld.bocmbci":           "中国银行",
	"com.chinamworld.main":              "建设银行",
	"com.ccb.ccbnetpay":                 "建设银行",
	"com.android.bankabc":               "农业银行",
	"com.android.bankabc.MainActivity":  "农业银行",
	"cmccwm.mobilemusic":                "咪咕音乐",
	"com.bocmacau":                      "中银澳门",
	"cmb.pb":                            "招商银行",
	"com.tencent.mobileqq.lite":         "QQ 极速版",
	"com.tencent.qqfwapp":               "腾讯服务平台",

	// ─── 出行 / 地图 ──────────────────────────────────────────
	"com.sdu.didi.psnger":               "滴滴出行",
	"com.didi.taxi":                     "滴滴打车",
	"com.baidu.BaiduMap":                "百度地图",
	"com.baidu.searchbox":               "百度",
	"com.baidu.netdisk":                 "百度网盘",
	"com.tencent.map":                   "腾讯地图",
	"com.google.android.apps.maps":      "Google 地图",

	// ─── 系统 / OPPO / ColorOS ─────────────────────────────────
	"android":                           "Android 系统",
	"com.android.systemui":              "System UI",
	"com.android.settings":              "设置",
	"com.android.phone":                 "电话",
	"com.android.vending":               "Play 商店",
	"com.android.chrome":                "Chrome",
	"com.android.providers.media.module": "媒体存储",
	"com.android.networkstack.tethering": "热点共享",
	"com.oplus.atlas":                   "Atlas",
	"com.oplus.statistics.rom":          "系统统计",
	"com.oplus.metis":                   "Metis",
	"com.oplus.games":                   "游戏空间",
	"com.oplus.appplatform":             "应用平台",
	"com.oplus.appdetail":               "应用详情",
	"com.oplus.battery":                 "电池管理",
	"com.oplus.camera":                  "相机",
	"com.heytap.htms":                   "HTMS",
	"com.heytap.market":                 "应用商店",
	"com.heytap.browser":                "OPPO 浏览器",
	"com.heytap.smarthome":              "智慧家庭",
	"com.coloros.calculator":            "计算器",
	"com.coloros.gallery3d":             "相册",
	"com.coloros.note":                  "便签",
	"com.coloros.weather2":              "天气",
	"com.coloros.alarmclock":            "时钟",
	"com.nearme.instant.platform":       "快应用",
	"com.nearme.gamecenter":             "游戏中心",
	"com.nearme.themespace":             "主题商店",
	"com.microsoft.appmanager":          "您的手机",
	"com.microsoft.bing":                "Bing",
	"com.microsoft.copilot":             "Copilot",
	"com.microsoft.office.outlook":      "Outlook",
	"com.microsoft.skydrive":            "OneDrive",

	// ─── AI / 国外 ───────────────────────────────────────────
	"com.anthropic.claude":              "Claude",
	"com.openai.chatgpt":                "ChatGPT",
	"com.google.android.apps.bard":      "Gemini",
	"com.google.android.googlequicksearchbox": "Google",
	"com.google.android.gm":             "Gmail",
	"com.google.android.youtube":        "YouTube",
	"com.google.android.youtube.tv":     "YouTube TV",
	"com.google.android.apps.youtube.music": "YouTube Music",
	"com.google.android.apps.docs":      "Google Docs",
	"com.google.android.calendar":       "Google Calendar",
	"com.google.android.apps.photos":    "Google 相册",
	"com.spotify.music":                 "Spotify",
	"com.facebook.katana":               "Facebook",
	"com.facebook.orca":                 "Messenger",
	"com.instagram.android":             "Instagram",
	"com.whatsapp":                      "WhatsApp",
	"org.telegram.messenger":            "Telegram",
	"org.thunderdog.challegram":         "Telegram X",
	"com.twitter.android":               "X (Twitter)",
	"com.linkedin.android":              "LinkedIn",
	"com.discord":                       "Discord",
	"com.reddit.frontpage":              "Reddit",
	"com.snapchat.android":              "Snapchat",
	"com.pinterest":                     "Pinterest",
	"com.netflix.mediaclient":           "Netflix",
	"com.amazon.mShop.android.shopping": "Amazon",
	"jp.pxv.android":                    "Pixiv",
	"jp.naver.line.android":             "LINE",

	// ─── VPN / 代理 ──────────────────────────────────────────
	"com.follow.clash":                  "Clash",
	"com.github.kr328.clash":            "Clash for Android",
	"org.metacubex.clash":               "Clash Meta",
	"com.github.shadowsocks":            "Shadowsocks",
	"com.v2ray.ang":                     "v2rayNG",
	"com.surfshark.vpnclient.android":   "Surfshark",
	"com.nordvpn.android":               "NordVPN",
	"com.expressvpn.vpn":                "ExpressVPN",
	"ch.protonvpn.android":              "Proton VPN",
	"net.openvpn.openvpn":               "OpenVPN",
	"com.wireguard.android":             "WireGuard",
	"com.tailscale.ipn":                 "Tailscale",
	"app.lawnchair":                     "Lawnchair Launcher",

	// ─── 开发 / 工具 ──────────────────────────────────────────
	"com.github.android":                "GitHub",
	"com.gitlab.gitlab":                 "GitLab",
	"com.termux":                        "Termux",
	"com.termux.api":                    "Termux:API",
	"com.termux.x11":                    "Termux:X11",
	"com.termux.boot":                   "Termux:Boot",
	"com.termux.styling":                "Termux:Styling",
	"me.weishu.kernelsu":                "KernelSU",
	"io.github.lsposed.manager":         "LSPosed",
	"de.robv.android.xposed.installer":  "Xposed Installer",
	"com.topjohnwu.magisk":              "Magisk",
	"com.omarea.vtools":                 "scene 工具箱",
	"com.omarea.gesture":                "手势工具",
	"com.android.documentsui":           "文件",
	"com.coloros.filemanager":           "文件管理",
	"com.jsharkc.gtweaker":              "GT 调整",

	// ─── 阅读 / 内容 ──────────────────────────────────────────
	"com.tencent.weread.full":           "微信读书",
	"com.qidian.QDReader":               "起点读书",
	"com.tencent.qqreader":              "QQ 阅读",
	"com.douban.book.reader":            "豆瓣阅读",
	"com.duokan.reader":                 "多看阅读",
	"com.idejian.book":                  "掌阅",

	// ─── 工具类 ───────────────────────────────────────────────
	"com.alicom.fusion.auth":            "阿里通信认证",
	"com.android.calendar":              "日历",
	"com.android.contacts":              "联系人",
	"com.android.dialer":                "拨号",
	"com.android.deskclock":             "时钟",
	"com.android.calculator2":           "计算器",
	"com.android.gallery3d":             "相册",
	"com.android.music":                 "音乐",
	"com.android.email":                 "邮件",
	"com.android.providers.calendar":    "日历存储",
}
